import type { Document, Clause, ChatMessage, ActivityItem, StatCard } from '@/types'

export const mockDocuments: Document[] = [
  {
    id: 1,
    name: 'Service Agreement Q4.pdf',
    size: '2.4 MB',
    pages: 24,
    date: 'Today, 10:23 AM',
    type: 'pdf',
    risk: 72,
    status: 'High Risk',
    parties: ['TechCorp Inc.', 'Vendor Solutions LLC'],
    effectiveDate: 'Jan 1, 2025',
    governingLaw: 'Delaware, USA',
    value: '$480,000',
    category: 'Service Agreement',
  },
  {
    id: 2,
    name: 'NDA Template 2024.pdf',
    size: '890 KB',
    pages: 8,
    date: 'Yesterday, 3:41 PM',
    type: 'pdf',
    risk: 38,
    status: 'Low Risk',
    parties: ['TechCorp Inc.', 'Acme Corp'],
    effectiveDate: 'Dec 1, 2024',
    governingLaw: 'New York, USA',
    value: 'N/A',
    category: 'Non-Disclosure Agreement',
  },
  {
    id: 3,
    name: 'Employment Contract.docx',
    size: '1.1 MB',
    pages: 14,
    date: 'Dec 18, 2:15 PM',
    type: 'docx',
    risk: 24,
    status: 'Low Risk',
    parties: ['TechCorp Inc.', 'John Doe'],
    effectiveDate: 'Jan 15, 2025',
    governingLaw: 'California, USA',
    value: '$120,000/yr',
    category: 'Employment Agreement',
  },
  {
    id: 4,
    name: 'Vendor Agreement.pdf',
    size: '3.2 MB',
    pages: 31,
    date: 'Dec 17, 9:00 AM',
    type: 'pdf',
    risk: 55,
    status: 'Medium Risk',
    parties: ['TechCorp Inc.', 'SupplyChain Co.'],
    effectiveDate: 'Feb 1, 2025',
    governingLaw: 'Texas, USA',
    value: '$1,200,000',
    category: 'Vendor Agreement',
  },
  {
    id: 5,
    name: 'SaaS License Agreement.pdf',
    size: '1.8 MB',
    pages: 19,
    date: 'Dec 15, 11:30 AM',
    type: 'pdf',
    risk: 61,
    status: 'Medium Risk',
    parties: ['TechCorp Inc.', 'SoftwareCo Ltd.'],
    effectiveDate: 'Jan 1, 2025',
    governingLaw: 'Delaware, USA',
    value: '$85,000/yr',
    category: 'Software License',
  },
]

export const mockClauses: Clause[] = [
  {
    id: 1,
    title: 'Termination Clause',
    risk: 'high',
    section: '8.2',
    text: 'Either party may terminate with 30 days written notice. However, company reserves right to terminate immediately for material breach, including failure to deliver services, insolvency, or confidentiality violation.',
  },
  {
    id: 2,
    title: 'Liability Limitation',
    risk: 'high',
    section: '9.1',
    text: 'Total liability shall not exceed fees paid in preceding 12 months. Consequential, indirect, or incidental damages excluded.',
  },
  {
    id: 3,
    title: 'Intellectual Property',
    risk: 'medium',
    section: '12.1',
    text: 'Work product created during term is work-for-hire. Ownership vests entirely in Client upon full payment.',
  },
  {
    id: 4,
    title: 'Auto-Renewal',
    risk: 'medium',
    section: '8.4',
    text: 'Agreement automatically renews for successive 12-month terms unless non-renewal notice given 60 days prior.',
  },
  {
    id: 5,
    title: 'Confidentiality',
    risk: 'low',
    section: '6.1',
    text: 'Both parties maintain confidentiality of proprietary information for 5 years post-termination.',
  },
  {
    id: 6,
    title: 'Dispute Resolution',
    risk: 'low',
    section: '15.1',
    text: 'Disputes resolved through good-faith negotiation, then binding arbitration under AAA rules in Delaware.',
  },
]

export const initialChatMessages: ChatMessage[] = [
  {
    id: 1,
    role: 'ai',
    text: "Hello! I'm LexIntel AI. I can analyze clauses, explain terms, identify risks, and answer contract questions.\n\nI have **Service Agreement Q4.pdf** loaded. What would you like to know?",
    timestamp: new Date(Date.now() - 120000),
  },
]

export const suggestedQuestions = [
  'Can I terminate this agreement early?',
  'What penalties exist for breach?',
  'Is there a confidentiality clause?',
  'What are the payment terms?',
  'Are there any auto-renewal clauses?',
  'Who owns the intellectual property?',
  'What is the governing law?',
]

export const dashboardStats: StatCard[] = [
  {
    label: 'Total Documents',
    value: '142',
    change: '+12 this month',
    trend: 'up',
    icon: '📄',
    color: '#E6F1FB',
    iconColor: '#185FA5',
  },
  {
    label: 'Analyses Run',
    value: '89',
    change: '+8 this week',
    trend: 'up',
    icon: '⚙️',
    color: '#E1F5EE',
    iconColor: '#0F6E56',
  },
  {
    label: 'Risk Alerts',
    value: '14',
    change: '3 unresolved',
    trend: 'down',
    icon: '⚠️',
    color: '#FCEBEB',
    iconColor: '#A32D2D',
  },
  {
    label: 'Avg. Risk Score',
    value: '41',
    change: '↓ 6 pts this month',
    trend: 'up',
    icon: '🛡️',
    color: '#FAEEDA',
    iconColor: '#854F0B',
  },
]

export const recentActivity: ActivityItem[] = [
  {
    id: 1,
    action: 'Document uploaded',
    document: 'Service Agreement Q4.pdf',
    user: 'Alex Chen',
    time: '10 min ago',
  },
  {
    id: 2,
    action: 'Analysis completed',
    document: 'NDA Template 2024.pdf',
    user: 'Alex Chen',
    time: '2 hrs ago',
  },
  {
    id: 3,
    action: 'Risk alert flagged',
    document: 'Vendor Agreement.pdf',
    user: 'System',
    time: '5 hrs ago',
  },
  {
    id: 4,
    action: 'Document shared',
    document: 'Employment Contract.docx',
    user: 'Sarah Kim',
    time: 'Yesterday',
  },
  {
    id: 5,
    action: 'Analysis completed',
    document: 'SaaS License Agreement.pdf',
    user: 'Tom Walsh',
    time: 'Yesterday',
  },
]
